package ru.mortihead.elastic.utils;

import java.util.Arrays;
import java.util.List;

public class BookConstants {
    public final static List<String> WORDS = Arrays.asList("There’s no question that getting a book as a present is great no matter what the title or when it happens. But what about those books that we’re given that are so special they alter the course of our lives in some way or change the way we think about the world? We spoke with some of our favorite authors about the book they received that has given them the most joy over the years.",
            "My dad gave me the novel Letting Go by Philip Roth. Dad read very little fiction—only one book of fiction a year. He was a political scientist, and he read dozens and dozens of non-fiction, academic books every year. But he always became enthusiastic about his one, annual book of fiction, which he would then recommend to everyone. He loved Roth. I like the novel, because it is Roth’s second—and unfamous—book; the writing shows his earnestness. He was looking for his voice then. I love the early novels of writers, for that same reason",
            "Knowing it is my favorite book, for my 34th birthday, a boyfriend once gave me a signed first edition of Erica Jong’s Fear of Flying.  Having always read tattered paperback versions, I had no idea the original was adorned with a spectacularly ornate cover that’s evocative of a Hieronymus Bosch.  I’m not a big collector of anything but no matter how often I pare down my belongings, I never get rid of this.  (Even though the boyfriend was long-ago lost to history, his accompanying birthday card remains tucked inside the book.",
            "One afternoon when I was seven years old, my mom and I went to our local bookshop, The Twig, in San Antonio, Texas, where she picked a book out for me that I was sure I was going to hate: Encyclopedia Brown, Boy Detective by Donald J. Sobol. But from the first page to the last, I was hooked, falling in love with Leroy Brown, Idaville’s ten-year-old boy sleuth, and I ended up owning every one of the twenty-eight books in the series. I was pretty good at figuring out the whodunits and decided that I was going to be a detective myself when I grew up. Instead, I became a writer, which, I see now, is a lot like being a detective, except that as a writer I have both to create the mystery and solve it at the same time. There’s a real art to writing suspense and while I’m not sure I’ll ever master it, I can definitely say that reading Encyclopedia Brown whet my appetite for it and taught me quite a lot about the form. Even now, I’m not sure that I would have been able to write, Tell Me How This Ends Well, my latest novel, if I hadn’t been exposed all those years ago to Leroy Brown",
            "When Breath Becomes Air by Paul Kalanithi. Kalanithi’s brave memoir chronicles in exquisite prose his brave battle with terminal illness, but rather than verge into depressing territory, it is a triumphant and inspiring read.  His words make one rethink our perception of time—to not only imagine what we might achieve in the future, but to cherish the beauty that surrounds us in the present",
            "On my eighth birthday my mother gave me a hardcover copy of The Adventures of Tom Sawyer. The inscription read: ‘Here is the brother you said you wanted.’ I was having trouble in school—particularly reading—and a psychologist had recently tested me and informed my mother and the school that I was, in the parlance of the day, ‘retarded.’ My mother steadfastly refused to accept this, saying, ‘You just haven’t found anything you care enough about to read.’ It turned out I was dyslexic and perhaps mildly autistic. It took me months, and when I was done, I could read, and I had indeed been given a brother—two, in fact, and I have visited with them every year since my eighth birthday",
            "Many years ago I was boarding a plane to Las Vegas, planning on doing two things I really enjoyed: gambling and reviewing All-You–Can-Eat buffets (I was young. Thankfully, I got both habits out of my system.). Also boarding was a large passenger sneezing and wheezing. Here was someone who desperately needed a bowl of chicken soup and a flight refund. While he squeezed his way down the aisle looking for his seat, everyone on the plane was thinking the same thing I was—I hope he doesn’t sit next to me. As he settled in next to me, I imagined the worst. Needless to say, by the end of the flight, we not only became friends who still keep in touch twenty years later, but he recommended a book which changed my life. During the flight, he sold me on In the Heart of the Sea by Nathaniel Philbrick. I asked my mom for this book for Christmas and as my Vegas friend promised, the book was extraordinary. So much so, it convinced me to write my own. Up until that point, I wrote comedy pieces and columns in publications but never anything long-form. Speed up to today—20 years later—In the Heart of the Sea has been adapted into a movie and now that I’ve finished my current project (Footnotes from the World’s Greatest Bookstores), I plan to publish that illustrated novel inspired by my favorite book. Called The Sea Below Us, it’s a black comedy about the missing Sir John Franklin. I sent a manuscript to Nathaniel Philbrick—whom I have also met and kept in touch with over the years—and thanked him for the inspiration his book provided. He loved the manuscript.",
            "My grandmother was a complicated woman—angry, loving, gossipy, and vibrant. She lived a country’s length away from me, and we were never close, even though I was named after her. The truth is, her mercurial moods scared me a little. One Christmas morning when I was 10 or so, I unwrapped a heavy package and discovered a beautiful hardcover book complete with illustrations: Little Women. On the inside was my grandmother’s inscription in handwriting as bold as she was: ‘For Sarah, with love.’ I devoured the book that day, then read it again and again. When I was immersed in its pages, I felt more connected to my grandmother than I ever had before; it was as if she truly saw me as the shy, book-loving girl I was, instead of the confident, outspoken one she perhaps wanted me to be. My grandmother died long ago, but I still have the worn, beloved copy of the novel she gave me, with her faded handwriting gracing the opening page. I cherish it still.",
            "When I was a kid, my step-dad, who raised me, used to buy me books as Christmas gifts. He was an intellectual from another era, and believed that some kind of moral salvation lay in a combination of books, public education, and paying as much taxes as you could. When I was in sixth grade, he bought me the trilogy of children’s books by E.B. White, which included Trumpet of the Swan, Charlotte’s Web, and Stuart Little. The same year, I got a satin comforter from my mom, and I remember lying in my antique brass bed, propped up on those luxurious new pillows, and going on the wild rides of these stories; it seems like I didn’t leave my bed until I’d finished all three. I’d always liked to read, but it was the experience of binging on those three children’s books that really showed me what reading did to me, and for me—the way reading made me feel calm and inspired before I knew what those words meant—and that I was, in my heart, a reader, which really, then, was the beginning of it all, since writers are just readers who need a job.",
            "In fifth grade, I received The Phantom Tollbooth by Norton Juster and spent the next three days wrapped up in the pages, unable to put it down. It was the first book that grabbed hold of me and didn’t let go. When I was a fifth grade teacher, I would read it aloud to my students every year and watch as the story of Milo and the mysterious Tollbooth grabbed them the way it grabbed me when I was that age. I still have that same weather-worn copy on my book shelf and look forward to the day I can hand it off to my son.");
    public final static List<String> AUTHORS = Arrays.asList("Erica Jong", "Philip Roth", "Donald Sobol",
            "Paul Kalanithi", "Mark Twain", "Nathaniel Philbrick", "Louisa May Alcott", "Norton Juster",
            "Graham Greene", "Robert McCloskey");
    public final static List<String> TITLES = Arrays.asList("One Morning in Maine", "Diet for a Small Planet",
            "The Heart of the Matter", "The Phantom Tollbooth", "Charlotte’s Web", "Little Women",
            "In the Heart of the Sea", "The Adventures of Tom Sawyer", "When Breath Becomes Air",
            "Encyclopedia Brown, Boy Detective");
}
